### ISSUE TITLE
Invalid Column Type using JBoss JNDI

### ISSUE THREAD

**Issue by rsrini7** [ironjacamar/ironjacamar#685]
Getting Invalid column type exception from below line with JBoss JNDI
`ocs.setObject(2, myPTracker);`

`java.sql.CallableStatement ocs = conn.prepareCall("BEGIN ? := pkg_tracker.start_tracker(?); END;");`
`ocs.registerOutParameter(1, ObjTracker._SQL_TYPECODE, ObjTracker._SQL_NAME);`
`ObjTracker myPTracker = new ObjTracker(conn);`
`myPTracker.setValueObject(pTracker);`
`ocs.setObject(2, myPTracker);`

> Caused by: java.sql.SQLException: Invalid column type
        at oracle.jdbc.driver.OraclePreparedStatement.setObjectCritical(OraclePreparedStatement.java:10495)
        at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:9974)
        at oracle.jdbc.driver.OraclePreparedStatement.setObjectInternal(OraclePreparedStatement.java:10799)
        at oracle.jdbc.driver.OracleCallableStatement.setObject(OracleCallableStatement.java:6097)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.setObject(OraclePreparedStatementWrapper.java:241)
        at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.setObject(WrappedPreparedStatement.java:1064)
        at com.test.PkgTracker.startTracker(PkgTracker.java:67)

**Comment by rsrini7** [comment]
Its due to Date and Timestamp issue. Closing
