### ISSUE TITLE
XAManagedConnection.end could loop endlessly when broadcasting error with MariaDB connector

### ISSUE THREAD

**Issue by tmurakam** [ironjacamar/ironjacamar#790]
When XAManagedConnection.end() is called and MariaDB connector throws error, it could loop endlessly and occur StackOverflowError.

```
2024-01-09T12:33:23.178638372Z stdout F         at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.xa.XAManagedConnection.end(XAManagedConnection.java:299)
2024-01-09T12:33:23.178639988Z stdout F         at org.jboss.jts//com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.delistResource(TransactionImple.java:912)
2024-01-09T12:33:23.178641551Z stdout F         at org.wildfly.transaction.client@2.0.1.Final//org.wildfly.transaction.client.LocalTransaction.delistResource(LocalTransaction.java:185)
2024-01-09T12:33:23.178643107Z stdout F         at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.listener.TxConnectionListener.haltCatchFire(TxConnectionListener.java:768)
2024-01-09T12:33:23.178644735Z stdout F         at org.jboss.ironjacamar.impl@1.5.3.Final//org.jboss.jca.core.connectionmanager.listener.AbstractConnectionListener.connectionErrorOccurred(AbstractConnectionListener.java:470)
2024-01-09T12:33:23.178646307Z stdout F         at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.broadcastConnectionError(BaseWrapperManagedConnection.java:691)
2024-01-09T12:33:23.178647857Z stdout F         at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.xa.XAManagedConnection.broadcastConnectionError(XAManagedConnection.java:203)
2024-01-09T12:33:23.178649416Z stdout F         at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.xa.XAManagedConnection$1.connectionErrorOccurred(XAManagedConnection.java:91)
2024-01-09T12:33:23.178651044Z stdout F         at org.mariadb//org.mariadb.jdbc.MariaDbPoolConnection.fireConnectionErrorOccurred(MariaDbPoolConnection.java:107)
2024-01-09T12:33:23.178652693Z stdout F         at org.mariadb//org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:312)
2024-01-09T12:33:23.178655795Z stdout F         at org.mariadb//org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
2024-01-09T12:33:23.178657406Z stdout F         at org.mariadb//org.mariadb.jdbc.client.impl.StandardClient.checkNotClosed(StandardClient.java:874)
2024-01-09T12:33:23.178659072Z stdout F         at org.mariadb//org.mariadb.jdbc.client.impl.StandardClient.sendQuery(StandardClient.java:485)
2024-01-09T12:33:23.178660628Z stdout F         at org.mariadb//org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:639)
2024-01-09T12:33:23.178662228Z stdout F         at org.mariadb//org.mariadb.jdbc.Statement.executeInternal(Statement.java:935)
2024-01-09T12:33:23.178663822Z stdout F         at org.mariadb//org.mariadb.jdbc.Statement.execute(Statement.java:1061)
2024-01-09T12:33:23.178665408Z stdout F         at org.mariadb//org.mariadb.jdbc.Statement.execute(Statement.java:452)
2024-01-09T12:33:23.178667053Z stdout F         at org.mariadb//org.mariadb.jdbc.MariaDbPoolConnection$MariaDbXAResource.execute(MariaDbPoolConnection.java:198)
2024-01-09T12:33:23.178668675Z stdout F         at org.mariadb//org.mariadb.jdbc.MariaDbPoolConnection$MariaDbXAResource.end(MariaDbPoolConnection.java:215)
2024-01-09T12:33:23.178670272Z stdout F         at org.jboss.ironjacamar.jdbcadapters@1.5.3.Final//org.jboss.jca.adapters.jdbc.xa.XAManagedConnection.end(XAManagedConnection.java:299)
... REPEAT ENDLESSLY ...
```

This looks very similar to https://issues.redhat.com/browse/JBJCA-1368.

I think a loop guard is required in `connectionErrorOccured()` declared in the constructor of XAManagedConnection class, like as https://github.com/ironjacamar/ironjacamar/pull/651

Version info:
* IronJacamar: 1.5.3 (WildFly 26.1.3.Final)
* MariaDB connector: 3.0.9

**Comment by tmurakam** [comment]
@tadamski 
Thank you for fix, but this does not fix the problem in our environment.

The problem is argument type of `broadcastConnectionError` is SQLException but not Exception.
`protected void broadcastConnectionError(SQLException e)`

So it is not called from XATransaction.end(), because exception type is XAException.

**Comment by tmurakam** [comment]
Thank you!
